ansible-pull-script: log if non-zero rsync return code

diff --git a/templates/ansible-pull-script.sh.j2 b/templates/ansible-pull-script.sh.j2
--- a/templates/ansible-pull-script.sh.j2
+++ b/templates/ansible-pull-script.sh.j2
@@ -90,9 +90,15 @@ fi
 # Mirror in the group_vars - they are copied to install node's www with the fgci-install tag and role for install node.
 # rsync assumes we are in $HOME/.ansible/pull/$WORKDIR when running
 /usr/bin/rsync -aqzH --delete --delay-updates rsync://{{ pull_install_ip }}/group_vars group_vars
+if [ "$?" != 0 ]; then
+        $loggercmd "error: rsync rsync://{{ pull_install_ip }}/group_vars rc=$?"
+fi
 
 # Mirror the host_vars tree
 /usr/bin/rsync -aqzH --delete --delay-updates rsync://{{ pull_install_ip }}/host_vars host_vars
+if [ "$?" != 0 ]; then
+        $loggercmd "error: rsync rsync://{{ pull_install_ip }}/host_vars rc=$?"
+fi
 
 # Install all the ansible role dependencies
 /usr/bin/curl -f -O http://{{ pull_install_ip }}/requirements_mirror.yml
