let's use a work directory - fixes #8
 - by default it puts in $HOME/.ansible/$(hostname -s)

diff --git a/templates/ansible-pull-script.sh.j2 b/templates/ansible-pull-script.sh.j2
--- a/templates/ansible-pull-script.sh.j2
+++ b/templates/ansible-pull-script.sh.j2
@@ -13,7 +13,7 @@ export https_proxy=$http_proxy
 export no_proxy="localhost,{{ pull_install_ip }},raw.githubusercontent.com"
 time=$[ ( $RANDOM % {{ ansible_pull_sleep }} )  + 1 ]
 lockdir="/var/lock/ansible-pull"
-SHOSTNAME=$(hostname -s)
+WORKDIR="workdir"
 
 # Command line option handling. Only -n (= no sleep, useful for
 # interactive use) is supported so far.
@@ -30,8 +30,8 @@ done
 
 
 # Setup the ansible-pull fgci work dir
-mkdir -p /root/.ansible/pull/$SHOSTNAME
-cd /root/.ansible/pull/$SHOSTNAME
+mkdir -p /root/.ansible/pull/$WORKDIR
+cd /root/.ansible/pull/$WORKDIR
 
 ## One ansible-pull at a time
 if ! mkdir "$lockdir"; then
@@ -53,12 +53,12 @@ fi
 git config --get remote.origin.url |grep {{ pull_install_ip }} >/dev/null
 if [ "$?" != 0 ]; then
     cd ..
-    rm -rf $(hostname -s)
-    /usr/bin/git clone http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git $SHOSTNAME
+    rm -rf $WORKDIR
+    /usr/bin/git clone http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git $WORKDIR
 if [ "$?" != 0 ]; then
-        $loggercmd "error: with 'git clone http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git $SHOSTNAME' PWD=$PWD rc=$?"
+        $loggercmd "error: with 'git clone http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git $WORKDIR' PWD=$PWD rc=$?"
 fi
-    cd $SHOSTNAME
+    cd $WORKDIR
 else
 # If the .git directory exists then only run git pull
 /usr/bin/git pull
@@ -68,7 +68,7 @@ fi
 fi
 
 # Mirror in the group_vars - they are copied to install node's www with the fgci-install tag and role for install node.
-# Wget assumes we are in $HOME/.ansible/pull/$SHOSTNAME when running
+# Wget assumes we are in $HOME/.ansible/pull/$WORKDIR when running
 /usr/bin/wget --no-host-directories --mirror --accept=example,yml,fgci-default-packages http://{{ pull_install_ip }}/group_vars
 
 # Mirror the host_vars tree
@@ -91,17 +91,17 @@ if [ "$?" != 0 ]; then
 fi
 
 # run the fgci-ansible/local.yml playbook, master branch and /root/hosts inventory file
-/usr/bin/ansible-pull -U http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git -C {{ ansible_pull_branch }} -i /root/hosts
+/usr/bin/ansible-pull -U http://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git -C {{ ansible_pull_branch }} -i /root/hosts -d /root/.ansible/pull/$WORKDIR
 pull_exit=$?
-$loggercmd "info: ansible-pull -U https://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git -C {{ ansible_pull_branch }} -i /root/hosts exited with rc=$pull_exit"
+$loggercmd "info: ansible-pull -U https://{{ pull_install_ip }}:8080/github.com/CSC-IT-Center-for-Science/fgci-ansible.git -C {{ ansible_pull_branch }} -i /root/hosts -d /root/.ansible/pull/$WORKDIR exited with rc=$pull_exit"
 
 {% if ansible_pull_grafana_annotation is defined %}
 {% if ansible_pull_grafana_annotation == true %}
 # Send a notification to cassini.fgci.csc.fi
 if [ "$pull_exit" == 0 ]; then
-  /bin/bash /root/.ansible/pull/$SHOSTNAME/tools/grafana_ansible_pull.sh succeeded
+  /bin/bash /root/.ansible/pull/$WORKDIR/tools/grafana_ansible_pull.sh succeeded
 else
-  /bin/bash /root/.ansible/pull/$SHOSTNAME/tools/grafana_ansible_pull.sh failed
+  /bin/bash /root/.ansible/pull/$WORKDIR/tools/grafana_ansible_pull.sh failed
 fi
 {% endif %}
 {% endif %}
